### ISSUE TITLE
Usage of Redis sentinel

### ISSUE THREAD

**Issue by wkloucek** [ONLYOFFICE/Kubernetes-Docs-Shards#18]
In the following I'm referring the state of [release/1.2.0](https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/tree/release/v1.2.0) branch with OO 8.2.0-rc25

I would like to use Redis Sentinel instead of plain Redis.

Therefore I would set following settings:

```yaml
connections:
  redisConnectorName: ioredis
  redisHost: rfs-redis
```

I had a look at the used lua library:

https://github.com/ledgetech/lua-resty-redis-connector?tab=readme-ov-file#connections-via-redis-sentinel

And I had a look at the code:

https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/blob/bc77cf40efb84f469cf812a4760e97b2129d710b/templates/ingresses/documentserver.yaml#L149

Seems like the lua code is not ready for Sentinel out of the box?

@alexanderonlyoffice Did I oversee something?

**Comment by alexonlyoffice** [comment]
@wkloucek, you are right. Redis Sentinel is not supported and we do not have time to include its support in the upcoming release. We will implement it in the next version.

**Comment by wkloucek** [comment]
> We will implement it in the next version.

What's the next version and it's rough ETA?

**Comment by alexonlyoffice** [comment]
@wkloucek, we are discussing the ETA. I will keep you updated.

**Comment by alexonlyoffice** [comment]
@wkloucek, we have prepared the test images of the version 8.2.2 where we added support for Redis Sentinel. You can take Helm from branch https://github.com/ONLYOFFICE/Kubernetes-Docs-Shards/tree/release/v2.1.0, the required images are uploaded to Docker Hub and have 8.2.2-4testing-sh1 tag. 

```
documentserver.initContainers.image.tag: 8.2.2-4testing-sh1
documentserver.docservice.image.tag: 8.2.2-4testing-sh1
documentserver.proxy.image.tag: 8.2.2-4testing-sh1
documentserver.converter.image.tag: 8.2.2-4testing-sh1
customBalancer.image.tag: 8.2.2-4testing-sh1
```

You will also need to add the following parameters for Redis Sentinel connection to the values.yaml, please find the example below: 

```
connections:
  redisConnectorName: ioredis
  redisHost: redis.default.svc.cluster.local
  redisPort: "26379"
  redisUser: default
  redisDBNum: "0"
  redisExistingSecret: redis
  redisSecretKeyName: redis-password
  redisNoPass: false
  redisSentinelGroupName: mymaster
  redisSentinelExistingSecret: redis
  redisSentinelSecretKeyName: redis-password
  redisSentinelUser: default
  redisSentinelPassword: ""
  redisSentinelNoPass: false

```
